trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md
    - docs/*
    - '*.md'

variables:
  buildConfiguration: 'Release'
  
  # Docker Configuration
  dockerRegistryServiceConnection: 'dafukDockerConnection'  # your Docker Hub service connection
  imageRepository: 'sh3r44/dafukspin-api'
  containerName: 'dafukspin-api'
  dockerfilePath: '$(Build.SourcesDirectory)/src/dafukSpin/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: BuildPush
    displayName: 'Build and Push'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'ubuntu-latest'   # cloud agent
    
    steps:
    - checkout: self
    
    # Build and Push Docker Image
    - task: Docker@2
      displayName: 'Build and Push Docker Image'
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        command: buildAndPush
        Dockerfile: '$(dockerfilePath)'
        buildContext: '$(Build.SourcesDirectory)'
        tags: |
          latest
          $(tag)
        arguments: '--build-arg BUILD_CONFIGURATION=$(buildConfiguration)'

- stage: Deploy
  displayName: 'Deploy to Homelab'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: 'Deploy to Homelab'
    pool:
      name: 'HomelabPool'
    
    steps:
    - checkout: none
    
    - script: |
        echo "Deploying dafukSpin API to homelab..."
        echo "Pulling latest image: $(imageRepository):latest"
        docker pull $(imageRepository):latest
        
        echo "Stopping existing container if running..."
        docker stop $(containerName) || true
        docker rm $(containerName) || true
        
        echo "Starting new container..."
        docker run -d \
          --name $(containerName) \
          -p 8080:8080 \
          -p 8081:8081 \
          --restart unless-stopped \
          --health-cmd="curl -f http://localhost:8080/health || exit 1" \
          --health-interval=30s \
          --health-timeout=10s \
          --health-start-period=30s \
          --health-retries=3 \
          $(imageRepository):latest
        
        echo "Container started successfully!"
        
        # Wait for container to be healthy
        echo "Waiting for container to be healthy..."
        timeout 120 bash -c 'until docker inspect --format="{{.State.Health.Status}}" $(containerName) | grep -q "healthy"; do echo "Waiting for health check..."; sleep 5; done' || {
          echo "Health check timeout - checking container logs:"
          docker logs $(containerName)
          exit 1
        }
        
        echo "✅ dafukSpin API deployed successfully and is healthy!"
        docker ps --filter "name=$(containerName)" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
      displayName: 'Pull and Run Container'
      
    # Optional: Clean up old images to save space
    - script: |
        echo "Cleaning up old Docker images..."
        # Keep last 3 images, remove older ones
        docker images $(imageRepository) --format "{{.Tag}}" | grep -v latest | tail -n +4 | xargs -r docker rmi $(imageRepository): || true
        
        # Remove dangling images
        docker image prune -f || true
        
        echo "Docker cleanup completed"
      displayName: 'Cleanup Old Images'
      continueOnError: true